## aim:- predicting which customers are leaving the bank

## for reference for keras follow youtube video(https://www.youtube.com/watch?v=qFJeN9V1ZsI) latest one

## note:- this OneHotEncoding is not working i have done a new method see it do something to clear the concept.

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\A-Z data sets\\P14-Part8-Deep-Learning (2)\\P14-Part8-Deep-Learning\\Section 35 - Artificial Neural Networks (ANN)\\Python\\Churn_Modelling.csv')

In [4]:
df.sample(5)

RowNumber  CustomerId      Surname  CreditScore Geography  Gender  Age  \
9372       9373    15775826      Iadanza          677    France    Male   30   
8842       8843    15610226       Fenton          614    France  Female   27   
9412       9413    15724648     Chikezie          725    France    Male   26   
8902       8903    15671973  Chukwuemeka          467     Spain    Male   39   
9687       9688    15771997       Bryant          791    France  Female   31   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9372       1   78133.15              1          0               1   
8842       9  106414.57              2          0               0   
9412       6   98684.15              1          0               0   
8902       5       0.00              2          1               1   
9687      10   75499.24              1          1               0   

      EstimatedSalary  Exited  
9372        174225.88       0  
8842         77500.81       0  
9412        133720.57       0  
8902          7415.96       0  
9687         22184.14       0

## we have installed these 3 libraries before implementing : Theno, Tensorflow, keras
## theano is for fast computing based on numpy lib, and it runs in both cpu and gpu. this feature is very usefull when runnig parallel computaion during forward and back propegation for deep learning. Tensorflow is also similar to Theano which is also for fast computaions.
## keras library is based on above two.

In [5]:
x=df.iloc[:,3:13].values
y=df.iloc[:,[-1]].values
x[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [6]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('ohe',OneHotEncoder(),[1])],remainder='passthrough')

x=ct.fit_transform(x)
x=x[:,1:]

In [8]:
x[1,:]

array([0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

## code for one hot encoding

## note:- the above code is completely new for me.

In [70]:
x.shape

(10000, 11)

In [71]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=0) 

In [72]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.fit_transform(x_test)

In [73]:
import keras  ## keras build the neural network based on tensorflow 
from keras import Sequential   ## sequential is used for initializing the neural network
from keras.layers import Dense ## Dense is used for build the layers of ANN

In [90]:
## initializing the neural network
classifier = Sequential([Dense(input_dim=11,output_dim=6,init='uniform',activation='relu'),
                        Dense(output_dim=6,init='uniform',activation='relu'),
                        Dense(output_dim=1,init='uniform',activation='sigmoid')])
## this step is adding the first hidden layer we first just form the skeleton of the neural network(this is the step)
## input_dim is the no.of nodes in the input layer(since we have 11 features so it is 11)
## output_dim we have choosen 6 this is the first hidden layer nodes we choosen it because (11+1)/2=6, but in actual we have to
#do it by parameter tuning
## note:- for the final layer we have used sigmoid function, but if our y(dependent variable has more than one feature we need 
# to use softmax as the activation function)

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=6, kernel_initializer="uniform")`
  
C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  after removing the cwd from sys.path.


## note:- the above syntax format i used is from the youtube video(https://www.youtube.com/watch?v=qFJeN9V1ZsI)

## adding the layers
## we are using RECTIFIER ACTIVATION functon for the hidden layers as in our andrew ng we use the SIGMOID FUNCTION as g(z) recap it. and here we are using the rectfier activation function for the hidden layers and sigmod activation function for the output layer.

## note:- for reference of visualization refer andrew ng notes

In [91]:
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 6)                 72        
_________________________________________________________________
dense_12 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [92]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
## optimizer:- it is the algorithm we use to do the optimization of our theta values(weights) here we are using stichiotic
# gradient decent by 'adam'
## loss function == cost function(andrew ng) 
## metrics:- the criterion we choose to evaluate our model performance

In [93]:
classifier.fit(x_train,y_train,batch_size=10,epochs=100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.4831 - accuracy: 0.7961
Epoch 2/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.4271 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4218 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.4181 - accuracy: 0.8189
Epoch 5/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.4155 - accuracy: 0.8270
Epoch 6/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.4139 - accuracy: 0.8306
Epoch 7/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.4128 - accuracy: 0.8304
Epoch 8/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.4118 - accuracy: 0.8321
Epoch 9/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.4106 - accuracy: 0.8338
Epoch 10/100
80

In [94]:
y_pred=classifier.predict(x_test)

In [99]:
y_pred=(y_pred>0.5)

In [100]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1527,   68],
       [ 204,  201]], dtype=int64)