In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\A-Z data sets\\P14-Part9-Dimensionality-Reduction\\Section 38 - Principal Component Analysis (PCA)\\Python\\Wine.csv')
df.sample(5)

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
169    13.40        4.60  2.86          25.0        112           1.98   
82     12.08        1.13  2.51          24.0         78           2.00   
141    13.36        2.56  2.35          20.0         89           1.40   
29     14.02        1.68  2.21          16.0         96           2.65   
40     13.56        1.71  2.31          16.2        117           3.15   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
169        0.96                  0.27             1.11             8.50  0.67   
82         1.58                  0.40             1.40             2.20  1.31   
141        0.50                  0.37             0.64             5.60  0.70   
29         2.33                  0.26             1.98             4.70  1.04   
40         3.29                  0.34             2.34             6.13  0.95   

     OD280  Proline  Customer_Segment  
169   1.92      630                 3  
82    2.72      630                 2  
141   2.47      780                 3  
29    3.59     1035                 1  
40    3.38      795                 1

In [18]:
x=df.iloc[:,:13].values
y=df.iloc[:,-1].values

In [19]:
x.shape

(178, 13)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=0)
#x_train.head()

In [21]:
from sklearn.preprocessing import StandardScaler
ss_x=StandardScaler()
x_train=ss_x.fit_transform(x_train)
x_test=ss_x.fit_transform(x_test)

## applying PCA

In [22]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)
explained_varience=pca.explained_variance_ratio_
explained_varience
## for every feature we get the feature varience by this

array([0.36884109, 0.19318394])

In [23]:
sum([0.36884109, 0.19318394])

0.56202503

## choosing 2 features will give good results so we put 2-principle components in the pca object they will explain 56% of the varience.

In [24]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state=0)
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
y_pred=lr.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[14,  0,  0],
       [ 1, 15,  0],
       [ 0,  0,  6]], dtype=int64)

## this confusion matrix given 3*3 matrix because we have 3 classes in the classification 1,2,3 here the this matrix meaning 14 true predictions(those are belonging to 1st class and similarly for 15,6 correct predictions for 2nd and 3rd classes respectively. here only one predicted wrong(that is the sampe bellongs to class 1 but predicted as class 2)

In [27]:
y_test

array([1, 3, 2, 1, 2, 2, 1, 3, 2, 2, 3, 3, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1], dtype=int64)

In [28]:
y_pred

array([1, 3, 2, 1, 2, 1, 1, 3, 2, 2, 3, 3, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1], dtype=int64)

## very good accuracy even reduing features from 13 --> 2